--CREACIÓN DE UNA TABLA NORMAL
CREATE OR REPLACE TABLE FORMACION.OBJETOS_BASICOS.CLIENTE (
   ID number,
   NOMBRE string,
   DIRECCION string,
   TELEFONO string
);

--INSERTAMOS 150 MILLONES DE REGISTROS
INSERT INTO FORMACION.OBJETOS_BASICOS.CLIENTE (ID,NOMBRE,DIRECCION,TELEFONO)
SELECT C_CUSTKEY, C_NAME, C_ADDRESS,C_PHONE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.CUSTOMER;

--COMANDO QUE MUESTRA LAS TABLAS DE UN ESQUEMA, TABLA, ETC ...
SHOW TABLES

--VEMOS MÉTRICAS DE TAMAÑO ACTIVO OCUPADO, TIME_TRAVEL Y FAILSAFE, ESTA VISTA NO MUESTRA LA INFORMACIÓN EN TIEMPO REAL, HAY QUE ESPERAR A QUE SE ACTUALICE
SELECT 	ID, 
       	TABLE_NAME, 
		TABLE_SCHEMA,
        TABLE_CATALOG,
		ACTIVE_BYTES / (1024*1024*1024) AS ACTIVE_STORAGE_USED_GB,
		TIME_TRAVEL_BYTES / (1024*1024*1024) AS TIME_TRAVEL_STORAGE_USED_GB,
		FAILSAFE_BYTES / (1024*1024*1024) AS FAILSAFE_STORAGE_USED_GB,
        IS_TRANSIENT,
        DELETED,
        TABLE_CREATED,
        TABLE_DROPPED,
        TABLE_ENTERED_FAILSAFE
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
WHERE TABLE_DROPPED is not null
ORDER BY FAILSAFE_BYTES DESC;
